configuration:
  web:
    server:
      port: 8080
      endpoints:
        healthcheck:
          name: Healthcheck
          path: /health
          enabled: true
        error_code:
          name: Error code
          path: /errors/:error_code
          enabled: true